version: "3.3"

services:

  postgres:
    image: postgis/postgis:12-3.0-alpine
    environment:
        - POSTGRES_DB=gltg_bmp
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=${DB_PASS}
    ports: 
        - 5432:5432
    networks:
      - bmp
    volumes:
    - postgres:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  bmp:

volumes:
  postgres:
