#!/usr/bin/env sh

help() {
    echo "Usage"
    echo "-h             show this help"
    echo "-d    --dev    set the environment to development and debug to true for the flask app"
    exit
}

export FLASK_DEBUG=0
export FLASK_ENV=production

for i in "$@"
do
    case $i in
    -h)
    help
    ;;
    -d|--dev)
    FLASK_DEBUG=1
    FLASK_ENV=development
    ;;
    esac
done

python app.py
